/* SOURCE ORACLE DATABASE */

-- CREATE DMS USER
CREATE USER AWS_DMS_USER IDENTIFIED BY SuperSecretPW01
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

ALTER USER AWS_DMS_USER QUOTA UNLIMITED ON USERS;

--GRANT DMS USER THE FOLLOWING PRIVILEGES
GRANT CREATE ANY PROCEDURE TO AWS_DMS_USER ;
GRANT CREATE ANY SEQUENCE TO AWS_DMS_USER ;
GRANT ALTER ANY TABLE TO AWS_DMS_USER ;
GRANT SELECT ANY TABLE TO AWS_DMS_USER ;
GRANT ALTER ANY SEQUENCE TO AWS_DMS_USER ;
GRANT DROP ANY TABLE TO AWS_DMS_USER ;
GRANT CREATE ANY SYNONYM TO AWS_DMS_USER ;
GRANT DROP ANY VIEW TO AWS_DMS_USER ;
GRANT ALTER ANY TRIGGER TO AWS_DMS_USER ;
GRANT CREATE ANY VIEW TO AWS_DMS_USER ;
GRANT INSERT ANY TABLE TO AWS_DMS_USER ;
GRANT CREATE ANY MATERIALIZED VIEW TO AWS_DMS_USER ;
GRANT DROP ANY PROCEDURE TO AWS_DMS_USER ;
GRANT CREATE ANY TRIGGER TO AWS_DMS_USER ;
GRANT CREATE ANY TABLE TO AWS_DMS_USER ;
GRANT CREATE ANY TYPE TO AWS_DMS_USER ;
GRANT CREATE ANY DIRECTORY TO AWS_DMS_USER ;
GRANT CREATE SESSION TO AWS_DMS_USER ;
GRANT SELECT ANY TRANSACTION TO AWS_DMS_USER;
GRANT SELECT ANY DICTIONARY TO AWS_DMS_USER;
GRANT SELECT on V_$ARCHIVED_LOG TO AWS_DMS_USER;
GRANT SELECT on V_$LOG TO AWS_DMS_USER;
GRANT SELECT on V_$LOGFILE TO AWS_DMS_USER;
GRANT SELECT on V_$DATABASE TO AWS_DMS_USER;
GRANT SELECT on V_$THREAD TO AWS_DMS_USER;
GRANT SELECT on V_$PARAMETER TO AWS_DMS_USER;
GRANT SELECT on V_$NLS_PARAMETERS TO AWS_DMS_USER;
GRANT SELECT on V_$TIMEZONE_NAMES TO AWS_DMS_USER;
GRANT SELECT on V_$TRANSACTION TO AWS_DMS_USER;
GRANT SELECT on ALL_INDEXES TO AWS_DMS_USER;
GRANT SELECT on ALL_OBJECTS TO AWS_DMS_USER;
GRANT SELECT on DBA_OBJECTS TO AWS_DMS_USER; /*(required if the Oracle version is earlier than 11.2.0.3) */ 
GRANT SELECT on ALL_TABLES TO AWS_DMS_USER;
GRANT SELECT on ALL_USERS TO AWS_DMS_USER;
GRANT SELECT on ALL_CATALOG TO AWS_DMS_USER;
GRANT SELECT on ALL_CONSTRAINTS TO AWS_DMS_USER;
GRANT SELECT on ALL_CONS_COLUMNS TO AWS_DMS_USER;
GRANT SELECT on ALL_TAB_COLS TO AWS_DMS_USER;
GRANT SELECT on ALL_IND_COLUMNS TO AWS_DMS_USER;
GRANT SELECT on ALL_LOG_GROUPS TO AWS_DMS_USER;
GRANT SELECT on SYS.DBA_REGISTRY TO AWS_DMS_USER;
GRANT SELECT on SYS.OBJ$ TO AWS_DMS_USER;
GRANT SELECT on DBA_TABLESPACES TO AWS_DMS_USER;
GRANT SELECT on ALL_TAB_PARTITIONS TO AWS_DMS_USER;
GRANT SELECT on ALL_ENCRYPTED_COLUMNS TO AWS_DMS_USER;
GRANT EXECUTE on DBMS_LOGMNR TO AWS_DMS_USER;
GRANT SELECT on V_$LOGMNR_LOGS TO AWS_DMS_USER;
GRANT SELECT on V_$LOGMNR_CONTENTS TO AWS_DMS_USER;


/* AS SYSDBA */
--ENABLE SUPPLEMENTAL LOGGING ON DATABASE LEVEL	
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (FOREIGN KEY) COLUMNS;

/* FOR ONGOING REPLICATION */
--ENABLE SUPPLEMENTAL LOGGING ON THE TABLE LEVEL FOR ALL TABLES THAT WILL BE REPLICATED ON AN ONGOING BASIS
ALTER TABLE DRWHO.TARDIS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER TABLE DRWHO.TARDIS ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER TABLE DRWHO.TARDIS ADD SUPPLEMENTAL LOG DATA (UNIQUE) COLUMNS;
